name: Build samples on supported zephyr boards

on: [push, pull_request]

jobs:
    run-command:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Zephyr project
          uses: zephyrproject-rtos/action-zephyr-setup@v1
          with:
            app-path: .
            toolchains: arm-zephyr-eabi

        - name: Build bluetooth samples for nrf5340dk board
          run: |
            west build -p -b nrf5340dk/nrf5340/cpuapp -d build_cpuapp samples/direction_finding_central/ -- -DEXTRA_CONF_FILE=overlay-aod.conf
            west build -p -b nrf5340dk/nrf5340/cpunet -d build_cpunet samples/hci_ipc/

        - name: Generate RAM report for build_cpuapp
          run: west build -d build_cpuapp -t ram_report

        - name: Generate ROM report for build_cpuapp
          run: west build -d build_cpuapp -t rom_report

        - name: Generate RAM report for build_cpunet
          run: west build -d build_cpunet -t ram_report

        - name: Generate ROM report for build_cpunet
          run: west build -d build_cpunet -t rom_report
