name: Build Sphinx Documentation

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install PlantUML dependencies
          run: |
            sudo apt install -y default-jre graphviz

        - name: Download PlantUML
          run: |
            wget https://sourceforge.net/projects/plantuml/files/plantuml.jar -O $HOME/plantuml.jar

        - name: Write PlantUML script
          run: |
            cat <<EOF > $HOME/plantuml
            #!/bin/sh
            java -jar /usr/local/bin/plantuml.jar "$@"
            EOF

        - name: Install PlantUML files
          run: |
            sudo cp $HOME/plantuml.jar /usr/local/bin/
            sudo cp $HOME/plantuml /usr/local/bin/
            sudo chmod +x /usr/local/bin/plantuml

        - name: Build Sphinx docs
          run: |
            cd doc
            pip install -r requirements.txt
            make html
